name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-darwin-amd64-v0.6.1.tar.gz
            - run: tar -C /usr/local/bin -xzvf dockerize-darwin-amd64-v0.6.1.tar.gz
            - run: rm dockerize-darwin-amd64-v0.6.1.tar.gz
            - run: docker build . -t test
            - run: docker run -d -p 3000:3000 --rm test
            - run: dockerize -timeout=200s -wait=http://localhost:3000/api
            - run: docker exec test npm run test
