name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker build . -t test
            - run: docker run -d -p 3000:3000 --rm test
            - run: sleep 30
            - run: docker exec test npm run test
